export const ERROR_MSG = {
    INVALIDPIN: "INVALID PIN",
    INVALID_NAME: "INVALID NAME ",
    INVALID_LENGTH: "INVALID LENGTH ",
    INVALID_EMAIL: "INVALID EMAIL ID ",
    INVITATION_SENT: "INVITATION SENT",
    CHILD_NOT_ADDED: "CHILD NOT ADDED",
    API_RESPONSE: "SOMETHING WENT WRONG",
    INVALID_USERNAME: "INVALID FULL NAME ",
    PLEASE_SELECT_ROLE: "PLEASE SELECT ROLE",
    SUPPROTED_FORMAT: "FORMAT NOT SUPPORTED",
    INVALID_UNAME_EMAIL: "INVALID UNAMEEMIL ",
    PLEASE_ENTER_EMAIL: "PLEASE ENTER EMAIL ID",
    CHILD_ALREADY_EXIST: "CHILD ALREADY EXISTS",
    INAVLIDE_CREDENTIALS: "INVALID CREDENTIAL ",
    PLEASE_ENTER_PIN: "PLEASE ENTER 4 DIGIT PIN",
    PLEASE_ENTER_PROFILE: "PLEASE ADD PROFILE PHOTO",
    SOMETHING_WENT_WRONG: "SOMETHING WENT WRONG",
    PLEASE_ADD_CHILD: "PLEASE ADD CHILD DETAILS",
    PASSWORDS_DONT_MATCH: "PASSWORDS DONT MATCH",
    SIMILAR_DATA: "ENTER DIFFERENT NAME AND ROLE",
    PLEASE_ENTER_PASSWORD: "PLEASE ENTER PASSWORD",
    PLEASE_ENTER_CREDENTIALS: "PLEASE ENTER DETAILS",
    EMAIL_ALREADY_REGISTER: "EMAIL ALREADY REGISTER ",
    NO_INTERNET: "PLEASE CHECK YOUR INTERNET CONNECTION",
    SIMILAR_CHILD_DATA: "ENTER DIFFERENT NAME OR GENDER",
    PLEASE_ENTER_PASSWORD_AGAIN: "PLEASE ENTER PASSWORD AGAIN",
    PASSWORD_CHECK: "YOUR NEW PASSWORD CANNOT BE SAME AS OLD PASSWORD",
    PLEASE_ENTER_6_DIGIT_PIN: "PLEASE ENTER 6 DIGIT PIN SENT ON YOUR EMAIL ID",
    INVALID_PWD:
        "YOUR PASSWORD MUST BE AT LEAST 8 CHARACTERS LONG, CONTAINS AT LEAST 1 NUMBER AND MUST BE A MIXTURE OF UPPERCASE AND LOWERCASE LETTERS",
};
export const MESSAGE_PASSING_EVENTS = {
    UPDATE_PROFILE: "updateProfile",
};

export const SUCCESS_MSG = {
    LOGIN: "LOGIN SUCCESSFULLY",
    LOGOUT: "LOGOUT SUCCESSFULL",
    DATA_UPDATE: "DATA UPDATED SUCCESSFULLY",
    PASSWORD_UPDATED: "PASSWORD UPDATED SUCCESSFULLY",
    PASSWORD_CHANGED: "PASSWORD CHANGED SUCCESSFULLY",
};
export const LOCAL_STORAGE = {
    TOKEN: "token",
    CHILD_ID: "childId",
    NEW_CHILDID: "newChild",
};
export const MESSAGE_CENTER_CUSTOM_EVENTS = {
    OPEN_SNACKBAR: "openSnackBar",
};
